services:
    oc_louvre.bookingcalcul:
        class: OC\LouvreBundle\Service\BookingCalcul
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    oc_louvre.stripe:
            class: OC\LouvreBundle\Service\Stripe
            public: true