<?php

namespace OC\LouvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TbookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbookingRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBookingByToken($btoken)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.btoken = :btoken')
            ->setParameter('btoken', $btoken['btoken']);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getTest($token)
    {
        $qb = $this->createQueryBuilder('a')
            //Jointure Tickets
            ->leftJoin('a.ttickets', 'tickets')
            ->addSelect('tickets')
            ->where('a.btoken = :btoken')
            ->setParameter('btoken', $token);

        return $qb->getQuery()->getArrayResult();
    }
}
