<?php

namespace OC\LouvreBundle\Repository;

/**
 * TticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TticketRepository extends \Doctrine\ORM\EntityRepository
{
}
